---
- block:
  - name: generate dhparam file if not exists
    command: "openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096"
    async: 3600
    args:
      creates: "/etc/ssl/certs/dhparam.pem"
  - name: install packages
    apt: "name=dehydrated state=latest"
  - name: add dehydrated cronjob
    copy:
      src: "dehydrated"
      dest: "/etc/cron.daily/dehydrated"
      mode: "0755"
      owner: "root"
      group: "root"
  tags:
    - letsencrypt
